# Generated by Django 2.1 on 2018-08-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instanca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_od', models.DateField()),
                ('datum_do', models.DateField()),
                ('konstanta', models.IntegerField(default=1)),
                ('potrosnja', models.IntegerField()),
                ('stanje_od', models.CharField(max_length=25, null=True)),
                ('stanje_do', models.CharField(max_length=25, null=True)),
                ('mrezarina', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Omm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.IntegerField()),
                ('adresa', models.CharField(max_length=50)),
                ('trafo', models.CharField(max_length=25, null=True)),
                ('brojilo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=25, null=True)),
                ('oib', models.IntegerField()),
                ('tvrtka', models.CharField(max_length=25, null=True)),
                ('adresa', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('broj', models.CharField(max_length=25, null=True)),
                ('kolicina', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=25)),
                ('mjesec', models.DateField()),
                ('rjt_rvt', models.DecimalField(decimal_places=4, max_digits=5)),
                ('oie', models.DecimalField(decimal_places=4, max_digits=5)),
                ('trnp', models.DecimalField(decimal_places=5, max_digits=6)),
                ('rvt_r1', models.DecimalField(decimal_places=2, max_digits=3)),
                ('naknada', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='racun',
            name='tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.Tarifa'),
        ),
        migrations.AddField(
            model_name='instanca',
            name='omm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.Omm'),
        ),
        migrations.AddField(
            model_name='instanca',
            name='racun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.Racun'),
        ),
    ]
