# Generated by Django 2.1 on 2018-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_svjetiljka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svjetiljka',
            name='snaga',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='svjetiljka',
            name='stup',
            field=models.CharField(max_length=5),
        ),
    ]
