# Generated by Django 2.1 on 2018-09-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0005_auto_20180831_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='svjetiljka',
            name='slika',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
