# Generated by Django 2.1 on 2018-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0006_svjetiljka_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svjetiljka',
            name='slika',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
