# Generated by Django 2.1 on 2018-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0007_auto_20180910_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svjetiljka',
            name='slika',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
