# Generated by Django 2.1.5 on 2019-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0008_auto_20180911_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('adresa', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
